# -*- coding: utf-8 -*-
"""Editorial layer (El Soco structure): image descriptions, audience selector, spreads, kickers. LV + EN."""
from content.data import T

# Long-form descriptions per image (short caption stays in data.py; this is the magazine text under the figure)
DESC = {
    'als-kettingskov-aerial': T('Astoņas Als mājas uz viena lauka Dienviddānijā. No gaisa redzams princips: viena forma, dažādas fasādes, katrai mājai savs zemesgabals un sava terase pret sauli.',
                                'Eight Als homes on one field in southern Denmark. From the air the principle is visible: one form, different facades, each house with its own plot and its own terrace facing the sun.'),
    'als70-front-dk': T('Als 70 Kettingskovā ar vitrīnu logiem visā gala fasādē. Terase zem jumta pagarina viesistabu uz āru; koka apšuvums ir dabīgā tonī, jumts — tumšs.',
                        'Als 70 in Kettingskov with full-height glazing across the gable. The covered terrace extends the living room outdoors; the cladding is natural wood, the roof dark.'),
    'als70-side-dk': T('Sānu skats parāda proporciju: 12,4 m garš korpuss, 25° jumts, 2,7 m sienas. Logi izvietoti pa telpām — guļamistabām mazāki, viesistabai vitrīna.',
                       'The side view shows the proportion: a 12.4 m body, 25° roof, 2.7 m walls. Windows follow the rooms — smaller for bedrooms, full-height for the living room.'),
    'als110-day-dk': T('Als 110 dienas gaismā: melna fasāde, koka detaļas ieejas zonā un terase, kas iet apkārt stūrim.', 'Als 110 by day: black facade, wood detailing at the entrance and a terrace wrapping the corner.'),
    'als110-evening-dk': T('Vakarā vitrīnu logi pārvērš māju par laternu — tas ir Als sērijas raksturīgākais skats.', 'At dusk the full-height windows turn the house into a lantern — the most recognisable Als view.'),
    'als110-evening2-dk': T('Tas pats vakars no cita leņķa. Apgaismojums terasē ir daļa no standarta komplektācijas.', 'The same evening from another angle. Terrace lighting is part of the standard specification.'),
    'als70-black': T('Als 70 ar ogļu melnu fasādi un tumšu metāla jumtu. Melnā versija ir populārākā Dānijā.', 'Als 70 in charcoal black with a dark metal roof. The black version is the most popular in Denmark.'),
    'als-kettingskov-development': T('Būvlaukums 2022. gada rudenī — pamatu plātnes gatavas, pirmie karkasi stāv.', 'The site in autumn 2022 — slabs ready, the first frames standing.'),
    'als-kettingskov-framing': T('Koka karkass ar vitrīnas ailu. Šeit redzams, cik daudz gaismas nes gala fasāde.', 'The timber frame with the glazing opening. This is where you see how much light the gable brings.'),
    'als-kettingskov-modular-assembly': T('Rūpnīcā ražoti sienu paneļi tiek uzstādīti ar celtni — viena māja dažās dienās.', 'Factory-built wall panels craned into place — one house in a few days.'),
    'als110-photo-lv-exterior-forest': T('Als 110 priežu mežā Latvijā, 2024. gads. Pelēka vertikāla dēļu fasāde un metāla jumts; māja stāv uz betona plātnes pamata.',
                                         'Als 110 in a pine forest in Latvia, 2024. Gray vertical board facade and a metal roof; the house stands on a concrete slab foundation.'),
    'als110-photo-lv-metal-roof': T('Metāla jumts ar stāvo falci — Als sērijas alternatīva betona dakstiņam. Vieglāks, klusāks lietū ar papildu izolāciju.',
                                    'Standing-seam metal roof — the Als alternative to concrete tile. Lighter, and quiet in rain with the extra insulation layer.'),
    'als110-photo-lv-kitchen': T('Virtuve ar melnām frontēm un salu. Virtuves mēbeles nav standarta paketē — šis ir klienta risinājums.', 'Kitchen with black fronts and an island. Kitchen furniture is not in the standard package — this is the client’s own choice.'),
    'als110-photo-lv-bedroom': T('Guļamistaba 15,6 m² ar logu uz mežu. Sienu apdare — krāsots ģipškartons, grīda — parkets.', 'The 15.6 m² bedroom with a window to the forest. Walls in painted plasterboard, floor in parquet.'),
    'als110-photo-lv-bathroom': T('Sanmezgls ar lielformāta flīzēm un dušu bez sliekšņa. Vannasistabas līmeņi Basic / Mid / Tailored ir katalogā.', 'Bathroom with large-format tiles and a walk-in shower. The Basic / Mid / Tailored bathroom levels are in the catalogue.'),
    'als110-photo-lv-staircase': T('Kāpnes uz mezanīnu — 17 m² klājs virs guļamistabām, ko izmanto kā darba vai viesu telpu.', 'Stairs to the mezzanine — a 17 m² deck above the bedrooms, used as a study or guest space.'),
    'als110-latvia-hallway': T('Ieejas gaitenis ar iebūvētiem skapjiem. Vējtveris ir 10 m² — vieta virsdrēbēm un tehnikai.', 'Entrance hall with built-in cupboards. The porch is 10 m² — room for coats and technical equipment.'),
    'als110-plus-latvia-exterior': T('Als 110+ — pagarināts korpuss ar individuālu plānojumu. Melna fasāde, koka ieejas niša, Latvijas karogs pie durvīm.', 'Als 110+ — an extended body with a custom layout. Black facade, wood entrance niche, the Latvian flag by the door.'),
    'als110-plus-latvia-terrace': T('Terase zem jumta ar kolonnu — pagarinātā versijā tā ir 20 m².', 'Covered terrace with a column — 20 m² in the extended version.'),
    'als110-plus-latvia-interior': T('Augstie griesti līdz korei un koka sijas. Grīda — parkets ķieģeļu rakstā.', 'Ceilings open to the ridge with timber beams. Herringbone parquet floor.'),
    'als110-plus-latvia-kitchen': T('Virtuve ar skatu uz viesistabu; galds pie vitrīnas loga.', 'Kitchen looking into the living room; the dining table by the full-height window.'),
    'als110-plus-latvia-facade-detail': T('Fasādes detaļa: vertikāli dēļi, melns tonis, logs ar tumšu rāmi.', 'Facade detail: vertical boards, black tone, window with a dark frame.'),
    'als110-plus-latvia-construction': T('Montāžas diena: paneļi tiek pacelti ar celtni, jumts seko tajā pašā nedēļā.', 'Assembly day: panels lifted by crane, the roof follows the same week.'),
    'als70-photo-solar-front': T('Als 70 ar saules paneļiem uz dienvidu jumta slīpuma — energoklase A kļūst par plus enerģiju.', 'Als 70 with solar panels on the south roof pitch — energy class A becomes energy-plus.'),
    'als70-photo-solar-terrace': T('Terase zem jumta pret dārzu. Koka klājs, melna fasāde.', 'Covered terrace towards the garden. Wood deck, black facade.'),
    'als70-photo-solar-windows': T('Vitrīnu logi no iekšpuses — grīda līdz griestiem, bez starpsienām.', 'The full-height windows from inside — floor to ceiling, no divisions.'),
    'als70-photo-solar-detail': T('Kores detaļa ar jumta pārkari un koka apšuvumu.', 'Ridge detail with the roof overhang and wood cladding.'),
    'als70-photo-solar-entrance': T('Ieeja ar nojumi un automašīnu piebraucamo.', 'Entrance with canopy and driveway.'),
    'aura-latvia-exterior': T('Aura sērijas māja pagarinātā korpusā Latvijā. Pelēka vertikāla fasāde, zems siluets, plakans jumta leņķis.', 'An Aura series house with an extended body in Latvia. Gray vertical facade, low silhouette, shallow roof angle.'),
    'aura-latvia-detail-1': T('Fasādes detaļa: dēļu ritms un logu rāmji vienā tonī.', 'Facade detail: board rhythm and window frames in one tone.'),
    'aura-latvia-detail-2': T('Ieejas durvis ievilktas fasādē — aizsargātas no lietus bez atsevišķas nojumes.', 'Entrance door recessed into the facade — sheltered from rain without a separate canopy.'),
    'energy-house-front-deck': T('Energy+ māja Stiklingenā: plakans jumts, koka fasāde, priekšējais klājs visā mājas garumā.', 'The Energy+ house in Stiklingen: flat roof, wood facade, a front deck the full length of the house.'),
    'energy-house-exterior': T('Fasāde no ceļa puses. Māja saražo vairāk enerģijas, nekā patērē.', 'The facade from the road. The house produces more energy than it uses.'),
    'energy-house-side-view': T('Sānu skats ar zemu siluetu pret debesīm.', 'Side view with the low silhouette against the sky.'),
    'energy-house-solar-panels': T('Saules paneļi uz plakanā jumta — pilns jumta laukums ir strādājošs.', 'Solar panels on the flat roof — the whole roof area works.'),
    'energy-house-terrace': T('Terase ar koka sienu un iebūvētu apgaismojumu.', 'Terrace with a timber wall and integrated lighting.'),
    'energy-house-detail': T('Koka fasādes detaļa — dēļi bez redzamiem stiprinājumiem.', 'Wood facade detail — boards with no visible fixings.'),
    'aurora-stiklingen-exterior': T('Aurora — 2019. gada individuālais projekts Dānijā: pirmā Frest māja ar plakanu jumtu un koka fasādi.', 'Aurora — a 2019 custom project in Denmark: the first Frest house with a flat roof and a wood facade.'),
    'aurora-stiklingen-interior': T('Interjers ar koka lameļu griestiem un vitrīnu uz dārzu.', 'Interior with timber slat ceiling and full-height glazing to the garden.'),
    'aurora-stiklingen-bathroom': T('Vannasistaba ar koka frontēm un piekaramo tualeti.', 'Bathroom with wood fronts and a wall-hung WC.'),
    'aurora-flat-roof-winter-2': T('Aurora ziemā — plakanais jumts un koka fasāde sniegā.', 'Aurora in winter — the flat roof and wood facade in snow.'),
    'custom-build-exterior-sunset': T('Individuāla māja Latvijā saulrietā: apmesta fasāde, koka akcenti, pagarināta auto nojume paviljona formā.', 'A custom house in Latvia at sunset: rendered facade, wood accents, an extended pavilion-style carport.'),
    'custom-build-carport-view': T('Auto nojume ar bruģētu piebraucamo — daļa no mājas jumta plaknes.', 'Carport with a paved drive — part of the house’s roof plane.'),
    'custom-build-corner-view': T('Stūra skats: gaišs apmetums un tumšs jumta apmale.', 'Corner view: light render and a dark roof edge.'),
    'custom-build-entrance-detail': T('Ieeja ar koka apšuvumu nišā.', 'Entrance with wood cladding in the niche.'),
    'custom-build-living-room': T('Viesistaba pirms mēbelēm — grīda, sienas un griesti Pilnās paketes līmenī.', 'Living room before furniture — floor, walls and ceiling at Complete-package level.'),
    'custom-build-insulation-walls': T('Sienu paneļi ar siltinājumu un tvaika barjeru pirms apdares.', 'Wall panels with insulation and vapour barrier before finishing.'),
    'factory-kit-assembly': T('Sienu panelis ceļā no kravas uz pamatu — rūpnīcas komplekts objektā.', 'A wall panel on its way from the truck to the slab — the factory kit on site.'),
    'factory-wall-construction': T('Tumšās fasādes sienu montāža ar sastatnēm.', 'Dark facade wall assembly with scaffolding.'),
    'factory-roof-installation': T('Jumta paneļa novietošana ar celtni — trīs cilvēki, viena diena.', 'Roof panel placed by crane — three people, one day.'),
    'factory-construction': T('Paneļu ražošana un montāža: karkass, siltinājums, apšuvums.', 'Panel production and assembly: frame, insulation, cladding.'),
    'juglas-bulvaris-completed': T('Juglasciema bulvāris, Rīga — uzbūvēta individuāla māja ar 115 m² dzīvojamo platību un koka fasādi.', 'Juglasciema bulvāris, Riga — a completed custom house with 115 m² of living space and a wood facade.'),
    'als110-interior-living': T('Als 110 virtuve‑viesistaba 43 m² — vizualizācija ar standarta apdari.', 'Als 110 kitchen–living, 43 m² — visualisation with standard finishes.'),
    'als110-interior-ground': T('1. stāva interjers ar skatu uz vitrīnu.', 'Ground floor interior looking towards the glazing.'),
    'als110-interior-loft': T('Mezanīns virs guļamistabām.', 'The mezzanine above the bedrooms.'),
    'aura70-hero': T('Aura 70 pilsētas apbūvē — kompakts, zems siluets starp esošām mājām.', 'Aura 70 in an urban setting — compact, low silhouette among existing houses.'),
    'aura110-hero': T('Aura 110 ar koka fasādi un terasi pret dārzu.', 'Aura 110 with a wood facade and terrace to the garden.'),
    'als70-hero': T('Als 70 laukos — melns jumts, koka fasāde, terase zem jumta.', 'Als 70 in the countryside — black roof, wood facade, covered terrace.'),
    'als110-hero': T('Als 110 no gaisa: garais korpuss, terase stūrī, dārzs apkārt.', 'Als 110 from the air: the long body, corner terrace, garden all round.'),
}

# "Kas jūs esat?" — audience selector (El Soco: Choose who you are)
AUDIENCES = [
    ('all', T('Visi', 'Everyone'), T('Māja, kas top rūpnīcā un mājās nonāk 16–20 nedēļās.', 'A house made in a factory that is home within 16–20 weeks.'),
     T('Frest ražo sienu un jumta paneļus sausos apstākļos, uzstāda tos objektā dažās dienās un nodod māju ar apdari, elektrību un apkuri. Četri modeļi, divas sērijas, cenas no 92 000 € ar PVN.',
       'Frest builds wall and roof panels indoors, assembles them on site in days and hands over the house with finishes, electrics and heating. Four models, two series, prices from €92,000 incl. VAT.'), 'model/als-110/', T('Sākt ar modeļiem →', 'Start with the models →')),
    ('family', T('Ģimene', 'Family'), T('Trīs guļamistabas, divi sanmezgli, viena atslēga.', 'Three bedrooms, two bathrooms, one key.'),
     T('Aura 110 vai Als 110 — 103–110 m², mezanīns bērniem vai darbam, terase zem jumta. Pilnā pakete nozīmē, ka pēc nodošanas jāieved tikai virtuve un mēbeles.',
       'Aura 110 or Als 110 — 103–110 m², a mezzanine for the children or for work, a covered terrace. The Complete package means only the kitchen and furniture come after handover.'), 'configure/', T('Kura māja man? →', 'Which house is mine? →')),
    ('first', T('Pirmā māja', 'First home'), T('Kompakta, energoefektīva, ar skaidru cenu.', 'Compact, energy-efficient, with a clear price.'),
     T('Aura 70 vai Als 70 — 68–72 m², divas guļamistabas, energoklase A un apkures izmaksas 280–430 € gadā. No 92 000 € ar PVN rūpnīcas komplektā ar montāžu.',
       'Aura 70 or Als 70 — 68–72 m², two bedrooms, energy class A and heating at €280–430 per year. From €92,000 incl. VAT as a factory kit with assembly.'), 'model/als-70/', T('Als 70 →', 'Als 70 →')),
    ('investor', T('Investors', 'Investor'), T('Dvīņu mājas, piebūves, vairāku māju apbūve.', 'Twin houses, annexes, multi-house developments.'),
     T('Aura 70 Urban — divas vienības uz viena zemesgabala. Als 110 Dual Homes. Kettingskovā astoņas Als mājas uzbūvētas vienā sezonā. Cenas un termiņi ir prognozējami, jo ražošana ir rūpnīcā.',
       'Aura 70 Urban — two units on one plot. Als 110 Dual Homes. In Kettingskov eight Als homes were built in one season. Prices and timelines are predictable because production is in the factory.'), 'projects/', T('Realizētie projekti →', 'Completed projects →')),
    ('plot', T('Zemes īpašnieks', 'Plot owner'), T('Zeme jau ir. Māja — 16–20 nedēļās.', 'You have the land. The house — in 16–20 weeks.'),
     T('Sākam ar novietojuma projektu, topogrāfiju un ģeotehnisko izpēti; pamatu plātne ir standarts. Kamēr top pamati, rūpnīcā jau top sienas.',
       'We start with the site plan, topography and geotechnical survey; the concrete slab is standard. While the foundations are built, the walls are already being made in the factory.'), 'resources/', T('Kā tas notiek →', 'How it works →')),
    ('pro', T('Arhitekts · Būvnieks', 'Architect · Builder'), T('Rūpnīcas komplekts ar dokumentāciju.', 'A factory kit with documentation.'),
     T('Pamata pakete: siltināti sienu paneļi (300 mm minerālvate), jumts, logi, ārdurvis, fasāde un montāža. Als 110 ārējie izmēri 16 700 × 8 600 mm, 25° jumts, energoklase A. Individuālus plānojumus projektējam uz Als vai Aura pamatnes.',
       'Base package: insulated wall panels (300 mm mineral wool), roof, windows, exterior doors, facade and assembly. Als 110 external dimensions 16,700 × 8,600 mm, 25° roof, energy class A. Custom layouts are designed on an Als or Aura base.'), 'custom-design/', T('Individuāli projekti →', 'Custom design →')),
    ('curious', T('Vienkārši interesē', 'Just curious'), T('Sāciet ar galeriju.', 'Start with the gallery.'),
     T('Astoņdesmit fotogrāfijas no uzbūvētām mājām Dānijā un Latvijā — ne renderi. Pēc tam salīdziniet četrus modeļus vienā tabulā.',
       'Eighty photographs of built houses in Denmark and Latvia — not renders. Then compare the four models in one table.'), 'gallery/', T('Galerija →', 'Gallery →')),
]

# Magazine spreads (full-bleed image + folio + kicker)
SPREADS = {
    'cover': {'img': 'als-kettingskov-aerial', 'folio': (T('Pirmais ciemats', 'The first village'), T('Kettingskov · Dānija · 2022', 'Kettingskov · Denmark · 2022')),
              'kicker': T('Viena forma. <em>Astoņas mājas.</em> Viena sezona.', 'One form. <em>Eight houses.</em> One season.')},
    'factory': {'img': 'factory-roof-installation', 'folio': (T('Rūpnīca', 'The factory'), T('Sienas · jumts · dažas dienas', 'Walls · roof · a few days')),
                'kicker': T('Sienas top sausumā. <em>Māja top dažās dienās.</em>', 'Walls are made indoors. <em>The house takes days.</em>'),
                'text': T('Katrs Frest sienu panelis tiek ražots rūpnīcā ar siltinājumu, tvaika barjeru un apšuvumu jau iekšā. Objektā paliek tikai montāža: celtnis, trīs cilvēki, nedēļa līdz jumtam. Tāpēc termiņš ir 16–20 nedēļas un cena ir zināma pirms pirmā rakuma.',
                          'Every Frest wall panel is made in the factory with insulation, vapour barrier and cladding already in it. On site only assembly remains: a crane, three people, a week to the roof. That is why the schedule is 16–20 weeks and the price is known before the first dig.'),
                'stats': [('300 mm', T('Siltinājums sienās', 'Wall insulation')), ('A', T('Energoklase', 'Energy class')), ('16–20', T('Nedēļas līdz atslēgām', 'Weeks to keys')), ('2', T('Valstis: LV · DK', 'Countries: LV · DK')), ('2019', T('Pirmā māja', 'First house')), ('4', T('Standarta modeļi', 'Standard models'))]},
    'word': {'img': 'als110-photo-lv-exterior-forest', 'pos': 'b', 'folio': (T('Vārds', 'The word'), 'Frest'),
             'kicker': T('Frest ir <em>fresh</em> un <em>forest</em>.', 'Frest is <em>fresh</em> and <em>forest</em>.'),
             'text': T('Nosaukums savieno svaigu gaisu un mežu — koku, no kura māja ir būvēta, un vietu, kur tā visbiežāk stāv. Frest mājas ir Dānijas dizaina skola, ražota Latvijā.',
                       'The name joins fresh air and forest — the wood the house is built from and the place it most often stands. Frest homes are the Danish design school, made in Latvia.')},  # CHECK etymology with Janis
}

KICKERS = {
    'models': T('Četri modeļi. <em>Divas sērijas.</em> Viena rūpnīca.', 'Four models. <em>Two series.</em> One factory.'),
    'idea': T('Rūpnīcas precizitāte ir produkts. <em>Māja ir formāts.</em>', 'Factory precision is the product. <em>The house is the format.</em>'),
}


# Focal point per image for object-fit crops: 'b' = keep bottom, 't' = keep top, 'c' = contain (plans/drawings)
POS = {
    'als110-photo-lv-exterior-forest': 'b', 'als110-plus-latvia-construction': 'b', 'als110-plus-latvia-exterior': 'b',
    'als110-plus-latvia-terrace': 'b', 'als110-photo-lv-kitchen': 'b', 'als110-photo-lv-metal-roof': 'b',
    'als70-photo-solar-entrance': 'b', 'als70-photo-solar-front': 'b', 'als70-photo-solar-terrace': 'b', 'als70-photo-solar-detail': 'b',
    'factory-kit-assembly': 'b', 'factory-roof-installation': 'b', 'energy-house-solar-panels': 'b', 'aura-latvia-detail-1': 'b',
    'als110-evening-dk': 'b', 'als110-evening2-dk': 'b', 'als110-day-dk': 'b',
    'als110-plan-ground': 'c', 'als110-interior-ground': 'c', 'als110-interior-loft': 'c', 'als110-loft-layout': 'c',
    'als70-plan-ground': 'c', 'als70-loft-layout': 'c', 'aura70-plan-ground': 'c', 'aura110-plan-ground': 'c', 'aura110-loft-layout': 'c',
    'aura70-3d-ground': 'c', 'aura70-3d-loft': 'c', 'aura110-3d-ground': 'c', 'aura110-3d-loft': 'c',
    'als110-base-config': 'c', 'als110-with-carport': 'c', 'als110-carport-right': 'c', 'als110-with-annex': 'c', 'als110-annex-garden': 'c', 'als110-dual': 'c',
}
